### ISSUE TITLE
Needs animated GIF!

### ISSUE THREAD

**Issue by colinta** [OTGApps/motion-imager#1]
No really that would be awesome, I don't understand what this does. :smiley:

**Comment by markrickert** [comment]
I was making one and got frustrated. What's your workflow for grabbing low-filesize, high quality animated gifs from the simulator?

**Comment by colinta** [comment]
I thought I was the only one who doesn't know how to do that!  Laurent might know, I'll ask him.

**Comment by colinta** [comment]
From Eloy: GIFBrewery

**Comment by markrickert** [comment]
Cool. bought it and it worked great. Well worth the $5!

**Comment by colinta** [comment]
Nice, I'll grab it then!  Seems like a good tool to have handy.

**Comment by markrickert** [comment]
Click this link so i get a cut of the purchase price ;) https://itunes.apple.com/us/app/gif-brewery/id435989461?mt=12&uo=4&at=10l4yY
