### ISSUE TITLE
Slide

### ISSUE THREAD

**Issue by Manueldjz** [OTGApps/motion-imager#3]
it is possible to put more than one picture with the same effects in the same view controller, or create a scroll view photo

**Comment by markrickert** [comment]
This gem uses the JTSImageViewController cocoapod which only supports one image at a time. This is more meant for the instances like on the twitter app where you're tapping to view an image larger, not for image galleries. I think there's probably something better out there for that, but I'm not sure what that thing is.

So unfortunately, this is not currently possible. If this feature is ever added to JTSImageViewController, we'll also support it in this gem.
