### ISSUE TITLE
uninitialized constant MotionImager::JTSImageViewControllerMode_Image (NameError)

### ISSUE THREAD

**Issue by eliduke** [OTGApps/motion-imager#4]
I am trying to implement this gem, and I'm getting the above error. I added it to my `Gemfile`, `bundle`, `rake pod:install`, and then added this to a cell trigger action:

```
MotionImager.new({
  url: attachment.url,
  placeholder: 'my_placeholder_image',
  presenting_from: WeakRef.new(self)
}).show
```

When I click on that cell, I get this error:

```
motion-imager.rb:54:in `modes': uninitialized constant MotionImager::JTSImageViewControllerMode_Image (NameError)
```

And the error eventually wiggles down to the `presenting_from` line.

Any thoughts?

**Comment by eliduke** [comment]
I tried the regular one as well:

```
MotionImager.new({
  image: UIImage.imageNamed('icon'),
  presenting_from: WeakRef.new(self)
}).show
```

And that one gave me the same error.

**Comment by markrickert** [comment]
You might have to do a `rake clean:all` and then `rake pod:install` again.

**Comment by eliduke** [comment]
Ugh. That was it. Thanks!

**Comment by markrickert** [comment]
:+1: RubyMotion can be finicky about recompiling things. If you ever see an error like that, just clean all and reinstall cocoapods and recompile. It works 100% of the time, 10% of the time!

**Comment by eliduke** [comment]
Haha. So true. Well, thanks for making the pod wrapper. This is awesome.

**Comment by markrickert** [comment]
You're very welcome!
